;; -*- mode: eask; lexical-binding: t -*-

(package "flymake-perlcritic"
         "1.0.3"
         "Flymake handler for Perl to invoke Perl::Critic")

(website-url "https://github.com/illusori/emacs-flymake-perlcritic")
(keywords "")

(package-file "flymake-perlcritic.el")

(script "test" "eask test ert flymake-perlcritic.el test/*.el")

(source "gnu")
(source "melpa")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
